Конструкция "switch"
MarinaIvantsova/learn.javascript.ru pull request #1
Opened 2022-06-06 13:58 UTC by MarinaIvantsova

2022-06-06 16:31 UTC, Londeren requested changes
Супер!
Есть пара предложений

2022-06-06 16:31 UTC, Londeren commented on switchCase/ifToSwitch.js
> +    case('0'):
Круглые скобки вокруг `case` не нужны.

Можно сразу преобразовать к числу и проверять числа, а не строки

2022-06-06 16:31 UTC, Londeren commented on switchCase/ifToSwitch.js
> +    console.log('Вы ввели число 0');
Поправь отступы

2022-06-06 16:31 UTC, Londeren commented on switchCase/switchToIf.js
> +} else if (browser === 'Chrome'
Попробуй использовать метод массива `includes` — ради интереса

2022-06-07 03:26 UTC, MarinaIvantsova commented on switchCase/ifToSwitch.js
> +    case('0'):
Если я преобразую к числу, то, если пользователь ничего не введет(пустая строка) - это преобразуется в ноль или если пользователь нажмет cancel/Esc, то null также преобразуется в 0.
Отсюда следует, что мы попадем в case(0) - и консоль выведет 'Вы ввели 0', но 0 не вводили.

2022-06-07 07:19 UTC, Londeren commented on switchCase/switchToIf.js
> +} else if (browser === 'Chrome'
Я имел в виду, что вместо 4 `browser === 'Chrome' || browser === 'Opera'…` использовать `includes`

2022-06-07 12:19 UTC, Londeren commented on switchCase/switchToIf.js
> +} else if (browser === 'Chrome'
```
browser === 'Chrome'
//     || browser === 'Firefox'
//     || browser === 'Safari'
//     || browser === 'Opera'
```

`['Chrome', 'Firefox', …].includes(browser)`

2022-06-08 16:07 UTC, merged