Null and undefined
MarinaIvantsova/learn.javascript.ru pull request #10
Opened 2022-06-16 12:40 UTC by MarinaIvantsova

2022-06-16 14:50 UTC, Londeren requested changes
Супер!

Есть пара комментариев

2022-06-16 14:50 UTC, Londeren commented on nullAndUndefined/determineTheTicketStatus.js
> +    } if (tickets[ticketId] === null) {
это что за форматирование? Забытый `else`?

2022-06-16 14:50 UTC, Londeren commented on nullAndUndefined/determineTheTicketStatus.js
> +
В конце функции после последнего выражения не нужна пустая строка.

2022-06-16 14:50 UTC, Londeren commented on nullAndUndefined/determineTheTicketStatus.js
> +console.log(ticketStatus(tickets, 'bfg'));
А вот в конце файла всегда оставляют одну пустую строку. Это не надо править, прост на будущее

2022-06-16 14:50 UTC, Londeren commented on nullAndUndefined/revokeTheTicket.js
> +   visitor.ticketId = null;
А как сделать без мутации параметра?

2022-06-20 15:18 UTC, MarinaIvantsova commented on nullAndUndefined/revokeTheTicket.js
> +   visitor.ticketId = null;
`function revokeTicket(visitor) {
  let copyVisitor = {...visitor};
  copyVisitor.ticketId = null;
   return copyVisitor;
}`

2022-06-20 15:21 UTC, merged