Декораторы
MarinaIvantsova/learn.javascript.ru pull request #32
Opened 2022-07-26 11:00 UTC by MarinaIvantsova

2022-08-01 15:06 UTC, Londeren requested changes
Отлично, есть небольшое предложение

2022-08-01 15:06 UTC, Londeren commented on decorators/delay.js
> +function f(x) {
Тут в целом в файле страдает форматирование. Поправь, пожалуйста

2022-08-02 02:40 UTC, MarinaIvantsova commented on decorators/delay.js
> +function f(x) {
Исправила

2022-08-03 14:24 UTC, Londeren approved these changes
👍

2022-08-04 04:54 UTC, merged