4я задача на Прототипное наследование
MarinaIvantsova/learn.javascript.ru pull request #37
Opened 2022-08-02 12:18 UTC by MarinaIvantsova

2022-08-03 14:32 UTC, Londeren requested changes
Отлично! Есть вопрос

2022-08-03 14:32 UTC, Londeren commented on prototype/hamster.js
> +        this.stomach = [food];
Что будет, если 2 раза вызвать `eat()`?

2022-08-04 04:53 UTC, MarinaIvantsova commented on prototype/hamster.js
> +        this.stomach = [food];
Значение food перезапишется на новое.

2022-08-04 04:53 UTC, MarinaIvantsova commented on prototype/hamster.js
> +        this.stomach = [food];
Значение свойства stomach, то есть, food перезапишется на новое значение.

2022-08-05 14:48 UTC, merged